#pytest.ini
[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    users: маркировка для тестов, связанных с пользователем.
    regression: маркировка для тестов, связанных с регрессионными тестами (или «регрессионными проверками»).
    authentication: тесты, связанные с аутентификацией.
    files: тесты связанные с файлами
