#pytest.ini
[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    users: маркировка для тестов связанных с пользователем
    regression: маркировка для тестов связанных с регресионными тестами
    authentication: тесты связанные с аунтификацией
